export type {
  AceitarEncaminhamentoComando,
  AlternarProntidaoComando,
  AnfitriaoSucedidoEvento,
  AutorizarRetornoComando,
  CodigoDeErro,
  Comando,
  ConsistenciaConfirmadaEvento,
  ConfirmarConsistenciaDaSalaComando,
  CriarSalaComando,
  DesconectarJogadorComando,
  EncaminhamentoFalhouEvento,
  EncaminhamentoIniciadoEvento,
  EncaminhamentoRecusadoEvento,
  EncaminharSalaComando,
  EncerrarSalaComando,
  EntrarNaSalaComando,
  ErroDeDominio,
  EstadoDaSala,
  EstadoDoLobby,
  EstadoDoVinculo,
  EventoDeDominio,
  EventoDeVinculo,
  ExpulsarMembroComando,
  ExpirarReconexaoComando,
  Membro,
  MembroDesconectadoEvento,
  MembroExpulsoEvento,
  MembroReconectadoEvento,
  MotivoDeEncerramento,
  ProntidaoAlteradaEvento,
  Presenca,
  RecusarEncaminhamentoComando,
  ReconectarJogadorComando,
  RegistrarFalhaDoEncaminhamentoComando,
  RegistrarReinicioDaSalaComando,
  ReinicioRegistradoEvento,
  Resultado,
  RetornoAutorizadoEvento,
  Sala,
  SalaEncaminhadaEvento,
  SalaExpiradaEvento,
  SairDaSalaComando,
  VinculoExpiradoEvento,
} from './lobby.ts';

export type {
  CelulasIluminadasEvento,
  CodigoDeErroDaPartida,
  ComandoDePartida,
  ConfirmarPosicaoDoPeaoComando,
  DesfechoDaPartida,
  EncerrarTurnoComando,
  ErroDeDominioDaPartida,
  EstadoDaPartida,
  EventoDaPartida,
  JogadorDaPartida,
  OperacaoBemSucedidaDaPartida,
  OperacaoRejeitadaDaPartida,
  PartidaTerminadaEvento,
  PosicaoConfirmadaEvento,
  ResultadoDaPartida,
  TurnoEncerradoEvento,
  TurnoIniciadoEvento,
} from './partida.ts';

// Alcance e Ataque dos Monstros (issue #172): a camada da Partida importa a
// resolução (monstros.ts → tabuleiro.ts, sem ciclos); os tipos do evento
// ataque_resolvido vivem no módulo e reentram na união EventoDaPartida.
export type {
  AtacanteDoAlcance,
  AtaqueResolvidoEvento,
  JogadorAlvoDoAtaque,
  ResolucaoDeAtaques,
} from './monstros.ts';

// Tipo de retorno de gerarRecebidas (declarado em peoes.ts, que não pode
// importar de tabuleiro.ts em runtime): estado com a Caixa consumida +
// pendências sorteadas + eventos peca_sorteada.
export type { RecebimentoGerado } from './peoes.ts';

export type {
  BordaCardinal,
  Celula,
  CodigoDeErroDeTabuleiro,
  ComandoDeTabuleiro,
  CorDoPeao,
  EntradaDoEstadoDoTabuleiro,
  ErroDeDominioDoTabuleiro,
  EscolherVagaDaPecaRecebidaComando,
  EstadoDoTabuleiro,
  EventoDoTabuleiro,
  FinalizarManipulacaoComando,
  GirarPecaComando,
  LimpezaAplicadaEvento,
  ManipulacaoFinalizadaEvento,
  MoverPeaoComando,
  OperacaoBemSucedidaDoTabuleiro,
  OperacaoRejeitadaDoTabuleiro,
  Orientacao,
  Peao,
  PeaoMovidoEvento,
  PeaoPermaneceuEvento,
  PeaoPosicionadoEvento,
  PeaoSelecionadoEvento,
  PecaDaCaixa,
  PecaDeselecionadaEvento,
  PecaGiradaEvento,
  PecaInicial,
  PecaPosicionada,
  PecaPosicionadaEvento,
  PecaRecebida,
  PecaSelecionadaEvento,
  PecaSorteadaEvento,
  PendenciaDeRecebimento,
  PermanecerComando,
  PosicionarPecaComando,
  PosicionarPeaoComando,
  RecebimentoGeradoEvento,
  ResultadoDoTabuleiro,
  SelecionarPecaComando,
  SelecionarPeaoComando,
  SentidoDeRotacao,
  TipoDaPeca,
  TipoDePecaDaCaixa,
  TipoDePecaDeCaminho,
  TipoDePecaEspecial,
  TipoDePecaDeMonstro,
  VagaDaPecaRecebidaEscolhidaEvento,
} from './tabuleiro.ts';

export {
  MOTIVOS_DE_ENCERRAMENTO,
  aceitarEncaminhamento,
  admitirMembro,
  alternarProntidao,
  aplicarComando,
  autorizarRetorno,
  confirmarConsistenciaDaSala,
  criarSala,
  desconectarJogador,
  encaminharSala,
  encerrarSala,
  entrarNaSala,
  expirarReconexao,
  expulsarMembro,
  estadoDoLobbyVazio,
  recusarEncaminhamento,
  reconectarJogador,
  registrarFalhaDoEncaminhamento,
  registrarReinicioDaSala,
  sairDaSala,
} from './lobby.ts';

export {
  aplicarComandoDePartida,
  avaliarTerminoDaPartida,
  estadoInicialDaPartida,
} from './partida.ts';

export {
  calcularAlcance,
  resolverAtaques,
} from './monstros.ts';

export {
  COMPOSICAO_DA_CAIXA,
  LADO_DA_GRADE,
  aplicarComandoDeTabuleiro,
  aplicarLimpeza,
  bordasAbertas,
  calcularIluminacao,
  ehPecaDeMonstro,
  estadoInicialDoTabuleiro,
  gerarRecebidas,
  sortearDaCaixa,
  vagasDisponiveis,
  vizinhasConectadas,
  vizinhos,
} from './tabuleiro.ts';
